Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/OneLineConditional:
  Enabled: false
AllCops:
  NewCops: enable
